name: Gatsby Build and Firebase Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build static files
      run: npm run build
      env:
        projectId: ${{ secrets.PROJECT_ID }}
        authDomain: auth.fraservotes.com
        databaseUrl: ${{ secrets.DATABASE }}
        storageBucket: ${{ secrets.STORAGE }}
        apiKey: ${{ secrets.API_KEY }}
        messagingSenderId: ${{ secrets.MESSAGING_ID }}
        appId: ${{ secrets.APP_ID }}
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
